"""
PROJECT: Germany's Electric Vehicle (EV) Charging Infrastructure Analysis
TEAM: Sathwik Nagasundra Sharma & Sai Surya Alla
COURSE: MSc. Artificial Intelligence in Industrial Application Bridge Semester 2025–2026
DATASET: Federal Network Agency (Bundesnetzagentur)
DISCLAIMER: This file is completely generated by AI (Gemini), only for practice for the presentation purposes! Not for submission.
PROMPT:
 I want you to make a single python file which contains all the explanation that you just gave in comments and the code itself.
For example if the code says:
top_operators = df.groupby("Betreiber")["AnzahlLadepunkteNLL"]
the comment above this must say
#.groupby("Betreiber"): This groups the entire dataset by the "Operator" name. Think of it like putting every receipt from "EnBW" in one folder and every receipt from "Tesla" in another.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import geopandas as gpd
import folium

# Ensure all columns are visible during data inspection
pd.set_option("display.max_columns", None)

# Load the dataset
# sep=";": The raw data from BNetzA uses semicolons as delimiters instead of commas.
df = pd.read_csv("ev_charging_germany.csv", sep=";", encoding="utf-8")

# -----------------------------------------------------------------------------------------
# 1. STATE-LEVEL ANALYSIS
# -----------------------------------------------------------------------------------------

def count_stations_per_state(df):
    """
    Counts the number of charging stations in each German state (Bundesland).
    """
    # .value_counts(): Counts every unique occurrence in the "Bundesland" column.
    # .sort_values(ascending=False): Sorts the results so the state with the most stations is first.
    stations_per_state = df["Bundesland"].value_counts().sort_values(ascending=False)
    return stations_per_state

def plot_stations_per_state(state_counts):
    """
    Generates a bar plot showing the distribution of stations by state.
    """
    plt.figure(figsize=(12, 6))
    
    # palette="viridis": Applies a sequential color map. 
    # NOTE: In Seaborn barplots, the first item in the sorted list (highest) 
    # gets the first color in the palette (Purple).
    sns.barplot(x=state_counts.values, y=state_counts.index, palette="viridis")
    
    plt.title("Charging Stations per German State")
    plt.xlabel("Number of Stations")
    plt.ylabel("State")
    plt.show()

# -----------------------------------------------------------------------------------------
# 2. CITY-LEVEL ANALYSIS
# -----------------------------------------------------------------------------------------

def find_top_city_excluding_majors(df, excluded_cities):
    """
    Identifies the leading city after removing major hubs like Berlin and Munich.
    """
    # ~df["Ort"].isin(excluded_cities): The '~' is a 'NOT' operator. 
    # It tells Pandas to keep rows where the city is NOT in our exclusion list.
    filtered_df = df[~df["Ort"].isin(excluded_cities)]

    # .value_counts().reset_index(): Counts the stations and turns the result 
    # from a Series into a DataFrame table for easy manipulation.
    city_counts = filtered_df["Ort"].value_counts().reset_index()
    city_counts.columns = ["city", "station_count"]

    # .iloc[0]: Selects the very first row (the new #1 city) from the sorted list.
    top_city = city_counts.iloc[0].to_dict()

    exclusion_str = ", ".join(excluded_cities)
    print("City with most charging stations (excluding " + exclusion_str + "): " + 
          top_city['city'] + " (" + str(int(top_city['station_count'])) + " stations)")


def summarize_amberg_stats(df, city_name="Amberg"):
    """
    Calculates total capacity and station count for a specific city.
    """
    # Filter the main table to only include rows for the specified city.
    amberg_df = df[df["Ort"] == city_name]

    # len(amberg_df): Counts the total number of rows (individual station locations).
    amberg_station_count = len(amberg_df)
    
    # .sum(): Adds up every value in the 'Power' column to find the total electrical capacity.
    amberg_max_power = amberg_df["InstallierteLadeleistungNLL"].sum()

    print("\n" + city_name + " total stations: " + str(amberg_station_count))
    print(city_name + " total maximum charging power (kW): " + str(amberg_max_power))


def plot_amberg_stations(df, city_name="Amberg", center_coords=[49.4478, 11.8583], zoom=13):
    """
    Creates an interactive map using Folium to show station locations.
    """
    amberg_df = df[df["Ort"] == city_name]
    
    # folium.Map: Initializes a Leaflet map centered on specific GPS coordinates.
    amberg_map = folium.Map(location=center_coords, zoom_start=zoom)

    # .iterrows(): A loop that visits every station in the city data one by one.
    for _, row in amberg_df.iterrows():
        popup_text = row['Betreiber'] + " (" + str(row['InstallierteLadeleistungNLL']) + " kW)"
        
        # folium.CircleMarker: Places a blue dot at the exact Breitengrad (Lat) and Laengengrad (Lon).
        folium.CircleMarker(
            location=[row["Breitengrad"], row["Laengengrad"]],
            radius=5,
            popup=popup_text,
            color="blue",
            fill=True
        ).add_to(amberg_map)

    return amberg_map

# -----------------------------------------------------------------------------------------
# 3. OPERATOR ANALYSIS
# -----------------------------------------------------------------------------------------

def find_top_operators(df):
    """
    Analyzes which companies operate the most charging points.
    """
    # .groupby("Betreiber"): Groups the entire dataset by the "Operator" name. 
    # Think of it like putting every station from "EnBW" in one folder and "Tesla" in another.
    # ["AnzahlLadepunkteNLL"]: Selects the column that counts the specific number of plugs (charging points).
    # .sum(): Adds all plugs together for each company to find total capacity.
    top_operators = (
        df.groupby("Betreiber")["AnzahlLadepunkteNLL"]
        .sum()
        .sort_values(ascending=False)
        .head(5)
    )
    
    print("Top 5 Charging Station Operators in Germany:")
    # enumerate(..., 1): A loop that automatically ranks the results (1, 2, 3...).
    for i, (operator, points) in enumerate(top_operators.items(), 1):
        print(f"{i}. {operator}: {points} vehicles can be charged at once")

def plot_top_operators(df):
    """
    Visualizes the top 5 operators in a horizontal bar chart.
    """
    top_operators = (
        df.groupby("Betreiber")["AnzahlLadepunkteNLL"]
        .sum()
        .sort_values(ascending=False)
        .head(5)
    )
    plt.figure(figsize=(10, 6))
    sns.barplot(x=top_operators.values, y=top_operators.index)
    plt.title("Top 5 Charging Station Operators in Germany", fontsize=14)
    plt.xlabel("Total Charging Points (Simultaneous Vehicles)")
    plt.ylabel("Operator")
    plt.show()

# -----------------------------------------------------------------------------------------
# EXECUTION
# -----------------------------------------------------------------------------------------

excluded_cities = ["Berlin", "Hamburg", "München", "Munich", "Köln", "Cologne"]

# Run Analysis
state_counts = count_stations_per_state(df)
plot_stations_per_state(state_counts)
find_top_city_excluding_majors(df, excluded_cities)
summarize_amberg_stats(df)
find_top_operators(df)
plot_top_operators(df)

# Generate Map
amberg_map = plot_amberg_stations(df)
# amberg_map.save("amberg_ev_map.html") # Uncomment to save the map as an HTML file